"""dodata tabela biblioteka

Revision ID: 1f3652e5c4d1
Revises: 5bd0aeb9e361
Create Date: 2026-04-23 12:51:11.397768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f3652e5c4d1'
down_revision = '5bd0aeb9e361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biblioteka',
    sa.Column('naziv', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('naziv')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('biblioteka')
    # ### end Alembic commands ###
