"""nova izmjena

Revision ID: ba05878438e9
Revises: 1f3652e5c4d1
Create Date: 2026-04-23 12:53:04.284632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba05878438e9'
down_revision = '1f3652e5c4d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biblioteka1',
    sa.Column('naziv', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('naziv')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('biblioteka1')
    # ### end Alembic commands ###
